import { useCallback, useEffect, useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import QRCode from 'react-native-qrcode-svg';
import { StyleSheet, Text, View } from 'react-native';
import { useNetInfo } from '@react-native-community/netinfo';

import { AppScreen } from '@/components/ui/app-screen';
import { BackButton } from '@/components/ui/back-button';
import { InlineNotice } from '@/components/ui/inline-notice';
import { LoadingSkeleton } from '@/components/ui/loading-skeleton';
import { PrimaryButton } from '@/components/ui/primary-button';
import { StatusPill } from '@/components/ui/status-pill';
import { generateCheckinToken } from '@/features/checkin/checkin-service';
import type { GeneratedCheckinToken } from '@/features/checkin/checkin-types';
import { useGroupLobby } from '@/features/groups/use-groups';
import { useAuth } from '@/providers/auth-provider';
import { useTheme } from '@/providers/theme-provider';
import { tokens } from '@/theme/tokens';

export default function HostCheckinScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const groupId = Array.isArray(id) ? id[0] : id;
  const { isDemo } = useAuth();
  const { theme } = useTheme();
  const network = useNetInfo();
  const lobby = useGroupLobby(groupId ?? '');
  const [token, setToken] = useState<GeneratedCheckinToken | null>(null);
  const [error, setError] = useState('');
  const [remaining, setRemaining] = useState(0);
  const [refreshKey, setRefreshKey] = useState(0);

  const backToLobby = useCallback(
    () => router.replace({ pathname: '/group/[id]', params: { id: groupId ?? '' } }),
    [groupId]
  );

  useEffect(() => {
    if (!groupId || network.isConnected === false) return;
    let active = true;
    let refreshTimer: ReturnType<typeof setTimeout> | undefined;

    const refresh = async () => {
      try {
        const next = await generateCheckinToken(groupId, isDemo);
        if (!active) return;
        setToken(next);
        setRemaining(
          Math.max(0, Math.ceil((new Date(next.expiresAt).getTime() - Date.now()) / 1000))
        );
        setError('');
        refreshTimer = setTimeout(() => void refresh(), 70_000);
      } catch {
        if (active) {
          setToken(null);
          setError(
            'A code can only be generated by the host during the event check-in window.'
          );
        }
      }
    };
    void refresh();
    return () => {
      active = false;
      if (refreshTimer) clearTimeout(refreshTimer);
    };
  }, [groupId, isDemo, network.isConnected, refreshKey]);

  useEffect(() => {
    const timer = setInterval(() => {
      setRemaining(
        token
          ? Math.max(
              0,
              Math.ceil((new Date(token.expiresAt).getTime() - Date.now()) / 1000)
            )
          : 0
      );
    }, 1000);
    return () => clearInterval(timer);
  }, [token]);

  const visibleToken = network.isConnected === false ? null : token;
  const progress = visibleToken ? Math.max(0, Math.min(1, remaining / 90)) : 0;

  return (
    <AppScreen>
      <BackButton label="Group lobby" onPress={backToLobby} />
      <StatusPill
        label={isDemo ? 'Demo QR · not live' : 'Host check-in'}
        tone={isDemo ? 'accent' : 'success'}
      />
      <Text style={[styles.title, { color: theme.text }]}>Group check-in</Text>
      <Text style={[styles.subtitle, { color: theme.textMuted }]}>
        {lobby.data?.title ?? 'Your confirmed activity'} · This code refreshes
        automatically.
      </Text>

      {network.isConnected === false ? (
        <InlineNotice
          icon="↯"
          tone="offline"
          message="You’re offline. Reconnect before presenting a secure check-in code."
        />
      ) : null}
      {isDemo ? (
        <InlineNotice message="This is a local preview QR. Scanning it does not record attendance or award XP." />
      ) : null}

      <View
        style={[
          styles.qrCard,
          { backgroundColor: theme.surfaceElevated, borderColor: theme.border }
        ]}
      >
        {visibleToken ? (
          <>
            <View
              accessible
              accessibilityLabel={`Active group check-in QR code. Expires in ${remaining} seconds.`}
              style={styles.qr}
            >
              <QRCode
                value={visibleToken.qrPayload}
                size={230}
                color="#111827"
                backgroundColor="#FFFFFF"
              />
            </View>
            <Text style={[styles.timer, { color: theme.primary }]}>
              Refreshes in {remaining} seconds
            </Text>
            <View
              accessibilityLabel={`${Math.round(progress * 100)} percent of code time remaining`}
              accessibilityRole="progressbar"
              accessibilityValue={{ min: 0, max: 100, now: Math.round(progress * 100) }}
              style={[styles.progressTrack, { backgroundColor: theme.surfaceMuted }]}
            >
              <View
                style={[
                  styles.progressFill,
                  { backgroundColor: theme.primary, width: `${progress * 100}%` }
                ]}
              />
            </View>
          </>
        ) : network.isConnected === false || error ? null : (
          <View style={styles.loadingState}>
            <LoadingSkeleton style={styles.qrSkeleton} />
            <LoadingSkeleton style={styles.timerSkeleton} />
          </View>
        )}
        {error ? (
          <View style={styles.errorState}>
            <Text style={[styles.errorTitle, { color: theme.text }]}>No active code</Text>
            <Text style={[styles.error, { color: theme.textMuted }]}>{error}</Text>
            <PrimaryButton
              label="Try again"
              variant="secondary"
              onPress={() => {
                setError('');
                setRefreshKey((current) => current + 1);
              }}
              style={styles.retry}
            />
          </View>
        ) : network.isConnected === false ? (
          <View style={styles.errorState}>
            <Text style={[styles.errorTitle, { color: theme.text }]}>
              QR paused while offline
            </Text>
            <Text style={[styles.error, { color: theme.textMuted }]}>
              No cached or expired credential will be shown.
            </Text>
          </View>
        ) : null}
      </View>
      <View
        style={[styles.safety, { backgroundColor: theme.surfaceMuted }]}
        accessibilityRole="summary"
      >
        <Text style={[styles.safetyTitle, { color: theme.text }]}>
          Keep the QR at the public venue
        </Text>
        <Text style={[styles.safetyCopy, { color: theme.textMuted }]}>
          Don’t screenshot or post it. Students should scan from this screen while the
          group is physically together.
        </Text>
      </View>
    </AppScreen>
  );
}

const styles = StyleSheet.create({
  title: {
    marginTop: tokens.space.md,
    fontSize: tokens.type.title,
    lineHeight: tokens.lineHeight.title,
    fontWeight: tokens.weight.bold,
    letterSpacing: -0.6
  },
  subtitle: {
    marginTop: tokens.space.sm,
    marginBottom: tokens.space.lg,
    fontSize: tokens.type.label,
    lineHeight: 21,
    fontWeight: tokens.weight.regular
  },
  qrCard: {
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: tokens.radius.lg,
    padding: tokens.space.xl
  },
  qr: {
    borderRadius: tokens.radius.md,
    backgroundColor: '#FFFFFF',
    padding: tokens.space.md
  },
  timer: {
    marginTop: tokens.space.md,
    fontSize: tokens.type.label,
    fontWeight: tokens.weight.bold
  },
  progressTrack: {
    width: 180,
    height: 6,
    overflow: 'hidden',
    borderRadius: tokens.radius.pill,
    marginTop: tokens.space.sm
  },
  progressFill: { height: '100%', borderRadius: tokens.radius.pill },
  loadingState: { width: '100%', alignItems: 'center' },
  qrSkeleton: { width: 262, height: 262, borderRadius: tokens.radius.md },
  timerSkeleton: { width: 150, height: 20, marginTop: tokens.space.md },
  errorState: {
    minHeight: 260,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: tokens.space.md
  },
  errorTitle: {
    fontSize: tokens.type.heading,
    fontWeight: tokens.weight.bold,
    textAlign: 'center'
  },
  error: {
    maxWidth: 300,
    marginTop: tokens.space.sm,
    fontSize: tokens.type.label,
    lineHeight: 20,
    textAlign: 'center'
  },
  retry: { minWidth: 180, marginTop: tokens.space.lg },
  safety: { borderRadius: tokens.radius.md, padding: tokens.space.lg, marginTop: 20 },
  safetyTitle: { fontSize: 16, fontWeight: tokens.weight.bold },
  safetyCopy: { marginTop: 5, fontSize: 13, lineHeight: 19 }
});
