import { useEffect, useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import QRCode from 'react-native-qrcode-svg';
import { StyleSheet, Text, View } from 'react-native';

import { AppScreen } from '@/components/ui/app-screen';
import { PrimaryButton } from '@/components/ui/primary-button';
import { generateCheckinToken } from '@/features/checkin/checkin-service';
import type { GeneratedCheckinToken } from '@/features/checkin/checkin-types';
import { useAuth } from '@/providers/auth-provider';
import { useTheme } from '@/providers/theme-provider';
import { tokens } from '@/theme/tokens';

export default function HostCheckinScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const groupId = Array.isArray(id) ? id[0] : id;
  const { isDemo } = useAuth();
  const { theme } = useTheme();
  const [token, setToken] = useState<GeneratedCheckinToken | null>(null);
  const [error, setError] = useState('');
  const [remaining, setRemaining] = useState(0);

  useEffect(() => {
    if (!groupId) return;
    let active = true;
    let refreshTimer: ReturnType<typeof setTimeout> | undefined;

    const refresh = async () => {
      try {
        const next = await generateCheckinToken(groupId, isDemo);
        if (!active) return;
        setToken(next);
        setError('');
        refreshTimer = setTimeout(() => void refresh(), 70_000);
      } catch {
        if (active) {
          setError(
            'A code can only be generated by the host during the event check-in window.'
          );
        }
      }
    };
    void refresh();
    return () => {
      active = false;
      if (refreshTimer) clearTimeout(refreshTimer);
    };
  }, [groupId, isDemo]);

  useEffect(() => {
    const timer = setInterval(() => {
      setRemaining(
        token
          ? Math.max(
              0,
              Math.ceil((new Date(token.expiresAt).getTime() - Date.now()) / 1000)
            )
          : 0
      );
    }, 1000);
    return () => clearInterval(timer);
  }, [token]);

  return (
    <AppScreen
      eyebrow="Host check-in"
      title="Scan together, on site"
      subtitle="This rotating code works only for confirmed members during the event window. A new code revokes the old one."
    >
      <View
        style={[
          styles.qrCard,
          { backgroundColor: theme.surface, borderColor: theme.border }
        ]}
      >
        {token ? (
          <>
            <View
              accessible
              accessibilityLabel={`Active group check-in QR code. Expires in ${remaining} seconds.`}
              style={styles.qr}
            >
              <QRCode
                value={token.qrPayload}
                size={230}
                color="#111827"
                backgroundColor="#FFFFFF"
              />
            </View>
            <Text style={[styles.timer, { color: theme.primary }]}>
              Refreshes in {remaining}s
            </Text>
          </>
        ) : (
          <Text style={[styles.loading, { color: theme.textMuted }]}>
            Creating a short-lived code…
          </Text>
        )}
        {error ? (
          <Text accessibilityRole="alert" style={[styles.error, { color: theme.danger }]}>
            {error}
          </Text>
        ) : null}
      </View>
      <View
        style={[styles.safety, { backgroundColor: theme.surfaceMuted }]}
        accessibilityRole="summary"
      >
        <Text style={[styles.safetyTitle, { color: theme.text }]}>
          Keep the QR at the public venue
        </Text>
        <Text style={[styles.safetyCopy, { color: theme.textMuted }]}>
          Don’t screenshot or post it. Students should scan from this screen while the
          group is physically together.
        </Text>
      </View>
      <PrimaryButton
        label="Back to lobby"
        variant="secondary"
        onPress={() =>
          router.replace({ pathname: '/group/[id]', params: { id: groupId ?? '' } })
        }
        style={styles.back}
      />
    </AppScreen>
  );
}

const styles = StyleSheet.create({
  qrCard: {
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: tokens.radius.lg,
    padding: tokens.space.xl
  },
  qr: {
    borderRadius: tokens.radius.md,
    backgroundColor: '#FFFFFF',
    padding: tokens.space.md
  },
  timer: { marginTop: tokens.space.md, fontSize: 16, fontWeight: '900' },
  loading: { paddingVertical: 120, fontSize: 15, fontWeight: '700' },
  error: {
    marginTop: tokens.space.md,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center'
  },
  safety: { borderRadius: tokens.radius.md, padding: tokens.space.lg, marginTop: 20 },
  safetyTitle: { fontSize: 16, fontWeight: '900' },
  safetyCopy: { marginTop: 5, fontSize: 13, lineHeight: 19 },
  back: { marginTop: tokens.space.lg }
});
